### ISSUE TITLE
If there is at least one all-day event, then ONLY all-day events get pulled

### ISSUE THREAD

**Issue by chrispytoes** [msigwart/gatsby-source-google-calendar#2]
The plugin works as expected when all events have a start and end time specified.

However, if just one event is marked as "All Day" with no start and end time, then ONLY all-day events are visible in the GraphQL API, and all other events are just missing entirely. As soon as I get rid of the all-day event, everything works again.

Suggestion: add an `allDay` boolean field to `CalendarEvent`

**Comment by msigwart** [comment]
Hey, thanks for the issue! I will look into it the next couple of days. An `allDay` flag sounds like a good solution.

Just out of curiosity, what's your use case for the all-day events?

**Comment by chrispytoes** [comment]
@msigwart This is a website for a client so it needs to be easy for them to use. If they post an all-day event on their calendar I don't want that to break it.

Something else I noticed too, the `description` field is missing from the schema when there is at least one all-day event as well.

Thanks for looking into it!

**Comment by chrispytoes** [comment]
@msigwart 

I've submitted a PR to fix this: #3

**Comment by msigwart** [comment]
Fixed by #3
