### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by djmtype** [msigwart/gatsby-source-google-calendar#6]
Please change in the README: 
`childCalendarEvent` is actually being used instead of `childrenCalendarEvent`.

**Comment by msigwart** [comment]
Thanks for the issue. Not sure I understand, could elaborate a bit?

**Comment by djmtype** [comment]
@msigwart The example query in your README would not work because the `childrenCalendarEvent` node does not exist. Use `childCalendarEvent` instead because that's the correct node name. In other words, it's called child not children.

[https://github.com/msigwart/gatsby-source-google-calendar/blob/main/README.md#4-accessing-calendars-and-events-in-your-site](https://github.com/msigwart/gatsby-source-google-calendar/blob/main/README.md#4-accessing-calendars-and-events-in-your-site)

**Comment by msigwart** [comment]
Oh okay, that's weird. In my example site, both nodes (child and children) exist and child only seems to return a single event? Anyway, I'll add a note to the README that people visit `http://localhost:8000/___graphql` to check out the created data and schema.

**Comment by djmtype** [comment]
@msigwart That is odd. What kind of Google Calendar account do you have – personal, Gsuite or an old Gsuite before Google started charging? I'm using the old Gsuite, BTW.

**Comment by msigwart** [comment]
Using a personal Google Calendar. So I guess it's a good idea to just use GraphiQL for constructing queries!

**Comment by djmtype** [comment]
Yep, better than blindly using the GraphQL Playground. 

Screenshot: 
![Screen Shot 10](https://user-images.githubusercontent.com/930713/104754429-320d3700-5727-11eb-8bb9-cfde1933228d.png)
