### ISSUE TITLE
Events not being updated after created

### ISSUE THREAD

**Issue by clariceabreu** [msigwart/gatsby-source-google-calendar#8]
I've already deployed my website using this plugin, but my events are not being updated on the website. 
When I add a new event on the calendar it doesn't appear on the site.

Is this a known issue? If so, how to fix it?

I even tried running locally and authenticating again, but the events don't appear

**Comment by clariceabreu** [comment]
Looking at the code I see that the events is only fetched once instead of subscribing to the calendar.
Therefore, only the events fetched on build will be displayed no matter a new event is created on the calendar.
Is this conclusion right?

**Comment by msigwart** [comment]
Hey @clariceabreu, sorry only saw this now. That is correct, you'll have to rebuild the site whenever you update the calendar! 

However, even when rebuilding the site you might still see some outdated events in the site (e.g. when you remove an event from the calendar). In that case it may help to run the command `gatsby clean` before building again.

Let me know if anything else comes up!
