### ISSUE TITLE
Have to run Gatsby Clean frequently to see updated events

### ISSUE THREAD

**Issue by avodynamics** [msigwart/gatsby-source-google-calendar#9]
Not sure why, but I have to run Gatsby Clean pretty frequently to get this plugin updating again. Sometimes no events come through until running clean, and sometimes an event that's been removed will persist while other events update.

This is happening locally, as well as when deployed on Netlify.
Is it possible to disable caching for this specific plugin?

**Comment by msigwart** [comment]
Well over two years later I finally took a look at the problem 😅  The fix is published in version 1.1.4 of the library.
